export const actionType = {
  //user
  SET_USER: "SET_USER",
  SET_USER_DETAIL: "SET_USER_DETAIL",
  SET_ME: "SET_ME",
  SET_USER_LOGIN: "SET_USER_LOGIN",

  //productType
  SET_PRODUCT_TYPE: "SET_PRODUCT_TYPE",
  SET_PRODUCT_TYPE_DETAIL: "SET_PRODUCT_TYPE_DETAIL",

  //product
  SET_PRODUCT: "SET_PRODUCT",
  SET_PRODUCT_DETAIL: "SET_PRODUCT_DETAIL",
  SET_PRODUCT_SEARCHED_BY_TYPE: "SET_PRODUCT_SEARCHED_BY_TYPE",

  //cart
  ADD_TO_CART: "ADD_TO_CART",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  INCREASE_QUANTITY: "INCREASE_QUANTITY",
  DECREASE_QUANTITY: "DECREASE_QUANTITY",

  //order
  SET_ORDER: "SET_ORDER",
  SET_ORDER_DETAIL: "SET_ORDER_DETAIL",


  SET_ORDER_PRODUCT : "SET_ORDER_PRODUCT",

  SET_ORDER_HISTORY : "SET_ORDER_HISTORY",

  //voucher
  SET_VOUCHER: "SET_VOUCHER",
  SET_VOUCHER_DETAIL: "SET_VOUCHER_DETAIL",

};
