import React from "react";
import * as yup from "yup";
import { useFormik } from "formik";
import LayoutAdminPage from "../../../../HOCs/LayoutAdminPage";
import { insertProductType } from "../../../../store/action/productTypes";

const schema = yup.object().shape({
  productTypeName: yup.string().required("Enter product type name !"),
  description: yup.string().required("Enter description !"),
});

const InsertProductType = (props) => {
  const {
    isValid,
    handleBlur,
    handleChange,
    values,
    errors,
    touched,
    setTouched,
  } = useFormik({
    initialValues: {
      productTypeName: "",
      description: "",
    },
    validationSchema: schema,
    validateOnMount: true,
  });

  const handleSubmit = (event) => {
    event.preventDefault();

    setTouched({
      productTypeName: true,
      description: true,
    });

    if (!isValid) return;

    const data = { ...values };

    insertProductType(data, props);
  };

  return (
    <LayoutAdminPage>
      <div className="container-fluid">
        <div className="row py-3">
          <span className="fs-2 fw-bolder">Insert Product Type</span>
        </div>
        <div className="row my-3">
          <form className="col-12 row">
            <div className="row col-12 col-md-6">
              <div className="col-12 my-2">
                <label className=" mb-2">Product Type Id: </label>
                <input
                  id="_id"
                  className="w-100  border border-warning p-2 "
                  value="Generated by server !"
                  disabled
                ></input>
              </div>
              <div className="col-12 my-2">
                <label className=" mb-2">Product Type Name: </label>
                <input
                  id="productTypeName"
                  className="w-100  border border-warning p-2 "
                  value={values.productTypeName}
                  onChange={handleChange}
                  onBlur={handleBlur}
                ></input>
                {touched.productTypeName && (
                  <p className="text-danger m-auto">{errors.productTypeName}</p>
                )}
              </div>
            </div>
            <div className="col-12 col-md-6 my-2">
              <label className=" mb-2">Description: </label>
              <textarea
                rows="5"
                cols="10"
                id="description"
                className="w-100  border border-warning p-2 "
                value={values.description}
                onChange={handleChange}
                onBlur={handleBlur}
              ></textarea>
              {touched.description && (
                <p className="text-danger m-auto">{errors.description}</p>
              )}
            </div>

            <div className="row">
              <button
                onClick={handleSubmit}
                className="col-3 btn btn-primary  border-2 p-2 mx-2 my-5 "
              >
                Insert Product Type<i class="fa fa-plus ms-4"></i>
              </button>
            </div>
          </form>
        </div>
      </div>
    </LayoutAdminPage>
  );
};

export default InsertProductType;
