import React from "react";
import * as yup from "yup";
import { useFormik } from "formik";
import LayoutAdminPage from "../../../../HOCs/LayoutAdminPage";
import { insertUserAction } from "../../../../store/action/users";

const schema = yup.object().shape({
  userName: yup.string().required("Enter username !"),
  password: yup.string().required("Enter password !"),
  email: yup.string().required("Enter email !").email("Enter email !"),
  phoneNumber: yup
    .string()
    .required("Enter phone number !")
    .matches(/^[0-9]+$/g, "Enter phone number !"),
  address: yup.string().required("Enter address !"),
  userType: yup.string().required("Enter type of user !"),
  fullName: yup.string().required("Enter fullname !"),
});

const InsertUser = (props) => {
  const {
    isValid,
    handleBlur,
    handleChange,
    values,
    errors,
    touched,
    setTouched,
  } = useFormik({
    initialValues: {
      userName: "",
      password: "",
      email: "",
      phoneNumber: "",
      address: "",
      userType: "",
      fullName: "",
    },
    validationSchema: schema,
    validateOnMount: true,
  });

  const handleSubmit = (event) => {
    event.preventDefault();

    setTouched({
      userName: true,
      password: true,
      email: true,
      phoneNumber: true,
      address: true,
      userType: true,
      fullName: true,
    });

    if (!isValid) return;

    const data = { ...values };

    insertUserAction(data, props);
  };

  return (
    <LayoutAdminPage>
      <div className="container-fluid">
        <div className="row py-3">
          <span className="fs-2 fw-bolder">Insert user</span>
        </div>
        <div className="row my-3">
          <form className="col-12 row">
            <div className="col-12 col-md-6 my-2">
              <label className=" mb-2">User Id: </label>
              <input
                id="_id"
                className="w-100  border border-warning p-2 "
                value="Generated by server !"
                disabled
              ></input>
            </div>
            <div className="col-12 col-md-6 my-2">
              <label className=" mb-2">Fullname: </label>
              <input
                id="fullName"
                className="w-100  border border-warning p-2 "
                value={values.fullName}
                onChange={handleChange}
                onBlur={handleBlur}
              ></input>
              {touched.fullName && (
                <p className="text-danger m-auto">{errors.fullName}</p>
              )}
            </div>
            <div className="col-12 col-md-6 my-2">
              <label className=" mb-2">Username: </label>
              <input
                id="userName"
                className="w-100  border border-warning p-2 "
                value={values.userName}
                onChange={handleChange}
                onBlur={handleBlur}
              ></input>
              {touched.userName && (
                <p className="text-danger m-auto">{errors.userName}</p>
              )}
            </div>
            <div className="col-12 col-md-6 my-2">
              <label className=" mb-2">Password: </label>
              <input
                id="password"
                className="w-100  border border-warning p-2 "
                value={values.password}
                onChange={handleChange}
                onBlur={handleBlur}
              ></input>
              {touched.password && (
                <p className="text-danger">{errors.password}</p>
              )}
            </div>

            <div className="col-12 col-md-6 my-2">
              <label className=" mb-2">Phone Number: </label>
              <input
                id="phoneNumber"
                className=" w-100  border border-warning p-2 "
                value={values.phoneNumber}
                onChange={handleChange}
                onBlur={handleBlur}
              ></input>
              {touched.phoneNumber && (
                <p className="text-danger">{errors.phoneNumber}</p>
              )}
            </div>
            <div className="col-12 col-md-6 my-2">
              <label className=" mb-2">Email: </label>
              <input
                id="email"
                className=" w-100  border border-warning p-2 "
                value={values.email}
                onChange={handleChange}
                onBlur={handleBlur}
              ></input>
              {touched.email && <p className="text-danger">{errors.email}</p>}
            </div>
            <div className="col-12 col-md-6 my-2">
              <label className=" mb-2">Address: </label>
              <input
                id="address"
                className=" w-100  border border-warning p-2 "
                value={values.address}
                onChange={handleChange}
                onBlur={handleBlur}
              ></input>
              {touched.address && (
                <p className="text-danger">{errors.address}</p>
              )}
            </div>
            <div className="col-12 col-md-6 my-2 ">
              <label className="">Type Of User: </label>
              <select
                id="userType"
                value={values.userType}
                onChange={handleChange}
                onBlur={handleBlur}
                className="w-100 p-2 border border-warning"
              >
                <option value="">
                  -- Select User Type --
                </option>
                <option value="Customer">Customer</option>
                <option value="Admin">Admin</option>
              </select>
            </div>

            <div className="row">
              <button
                onClick={handleSubmit}
                className="col-3 btn btn-primary  border-2 p-2 mx-2 my-5"
              >
                Insert User<i class="fa fa-plus ms-4"></i>
              </button>
            </div>
          </form>
        </div>
      </div>
    </LayoutAdminPage>
  );
};

export default InsertUser;
